### ISSUE TITLE
double quotes followed by punctuation

### ISSUE THREAD

**Issue by alexisargyris** [davidmerfield/Typeset#10]
When double quotes are followed by a punctuation mark (e.g. comma or period), they are rendered as opening, instead of closing, double quotes.

**Comment by davidmerfield** [comment]
This can be fixed in [quotes.js](https://github.com/davidmerfield/Typeset/blob/master/src/quotes.js#L14). I'll look into it later.

**Comment by alexisargyris** [comment]
i'd like to help but it looks a bit overwhelming...
