### ISSUE TITLE
Can't use typeset-js on OS X 10.10.5

### ISSUE THREAD

**Issue by starkshaw** [davidmerfield/Typeset#22]
I executed this:
`$ npm install -g typeset`
And I got
```
typeset@0.1.4 /usr/local/lib/node_modules/typeset
├── html-entities@1.1.3
├── hypher@0.2.3
└── cheerio@0.19.0 (entities@1.1.1, dom-serializer@0.1.0, css-select@1.0.0, lodash@3.10.1, htmlparser2@3.8.3)
```

But I don't have `typeset-js` when I tried to run it:
`zsh: command not found: typeset-js`

OS X 10.10.5, iTerm 2, with Oh-My-Zsh.

**Comment by davidmerfield** [comment]
I've just pushed the latest version to NPM – it should work now. Let me know if not

**Comment by starkshaw** [comment]
@davidmerfield It is working now. Thanks for your contribution.

**Comment by davidmerfield** [comment]
:+1:
