### ISSUE TITLE
Black magic

### ISSUE THREAD

**Issue by Offirmo** [davidmerfield/Typeset#24]
This lib looks great ! But I don't believe in neither fairy tales nor magic.

I won't pass my content in a "black box" that magically promises enhancements.

Could you explain (blog post ?) exactly what problem does your library solve and how ?

Thanks

**Comment by davidmerfield** [comment]
I will be writing a post about the techniques used in this library in the next few days. I'll post a link here when it's published

**Comment by alexisargyris** [comment]
Please don't forget to specify exactly which character combinations you recognise as valid input for processing and to which characters you translate them. A case in point is quotes (e.g. single, double, space before, space after, spaces on both sides, no spaces, etc.).

**Comment by Offirmo** [comment]
@davidmerfield :+1:

**Comment by Offirmo** [comment]
Questions I have :
- what if I'm already doing properly some of the stuff ? (good quotes, good non-breaking spaces)
- Is it locale-dependant ? (for ex. french quotes are not like english quotes) If not, is it parameterizable with a set of rules ?

**Comment by davidmerfield** [comment]
What do you mean some kink of auto-correct?

Blot uses a set of regular expressions to handle punctuation replacement. You can pass in text with 'correct' quotes, or text with a mixture of 'correct' and 'incorrect' quotes. Everything ought to work correctly. 

It's not locale dependent, yet.

**Comment by Offirmo** [comment]
some *kind*. I.m looking for your blog post !

**Comment by fiatjaf** [comment]
This issue is kinda agressive.

"I won't pass my content", well, no one is asking you to do that.
"black box", no, the source is there, you can read it if you want.

**Comment by Offirmo** [comment]
@fiatjaf I'm completely sorry. I didn't mean to be rude. Filing an issue, for me, is showing my interest ! Like I said at the beginning "This lib looks great !".

I'm mot a native english speaker and I may have missed some subtleties in my writing.

I apologize sincerely. I'll try to be more careful with my phrasing in the future.

**Comment by davidmerfield** [comment]
I'm closing this for now as I work through the issues on the repo. Follow [me on twitter](https://twitter.com/lllIIlIlIl) to be notified of the blog post.
