### ISSUE TITLE
Markdown

### ISSUE THREAD

**Issue by fiatjaf** [davidmerfield/Typeset#27]
I imagine that Typeset processing would work well with raw markdown. It seems so, but maybe I'm wrong.

Is there something I should be worried about if preprocessing markdown with Typeset? (Maybe something that would break markdown -- the `\n\n---\n\n` that represents an `<hr>`, for example.)

**Comment by davidmerfield** [comment]
Hi @fiatjaf! This library is designed to process HTML. Some of the punctuation replacement might be useful for Markdown. However, for the moment, processing markdown is beyond the scope of the project. Don't let that stop you from starting your own fork – let me know if you do! 

Am going to close this for now.
