### ISSUE TITLE
Build file

### ISSUE THREAD

**Issue by sebastien** [davidmerfield/Typeset#3]
The `build.js` script does not see to produce any `.js` file and hangs after outputting "done". It also depends on numerous non-listed Node modules.

``` 
js build.js
BUILDING!
DONE!
[Have to type Ctrl-C to exit]
```

**Comment by davidmerfield** [comment]
Just added instructions to the readme.

I've moved build.js to clear up any possible confusion – that script was for building the demo page. The library's source is located in ```/src``` and doesn't really require building, just run ```npm install``` to fetch all the dependencies. I believe all the non-native modules are listed in package.json.

**Comment by sebastien** [comment]
Well, it would be good to have build file to generate a `typeset-0.0.0.js` file to be embedded as-is for people who don't use `npm` or `require`.

**Comment by davidmerfield** [comment]
Good idea, I'll do this

**Comment by eugene-eeo** [comment]
@sebastien "embedded as is" being client side or server side module?

**Comment by davidmerfield** [comment]
I'm going to assume client? Can't see a point for it otherwise.

**Comment by sebastien** [comment]
Yes, precisely.

**Comment by gabrielperales** [comment]
In the last update that I made, you can find a build for client side.

**Comment by mikerockett** [comment]
Hi David - I don't want to create a new issue as I'd just like to follow up. The current client-build is quite far behind, and I'd like to use the exclusions array. Any chance this can be updated, or are there issues with making it client-compatible at the moment?

For some insight, I was using Smartypants on the server side before, but I much prefer the output of this package - really is neat. 😁
