### ISSUE TITLE
En-dash for number ranges

### ISSUE THREAD

**Issue by samhenrigold** [davidmerfield/Typeset#72]
I was planning to add a line in punctuation.js to replace a hyphen between two numbers _without a space_ with an en-dash (`14-31 days ` → `"14&ndash;31 days"`).

It looks like for ranges with a space, we're expecting it to be replaced with an em-dash. I'm unsure if this is by design but [the test HTML](https://github.com/davidmerfield/Typeset/blob/ac79d6ed7e78e1bea07649b91c42138e10e3d95a/test/punctuationSpec.js#L39) (and the Chicago style) calls for an en-dash. Should this be corrected or is there a different rule for ranges with spaces that I'm missing?

Thanks!

**Comment by danielhaim1** [comment]
That sounds interesting, I would like to investigate this further. Found some very nice notes [here](https://www.grammarly.com/blog/en-dash/) too, I'm adding some others below:

## Dash in Dates & Numbers

- Between times: 1200&ndash;1600
- Between times: 6 am&ndash;8 am
- Between days: Monday&ndash;Friday
- Between dates: 12&ndash;15 October
- Between months: June&ndash;August
- Between years: 1967&ndash;1969

## Dash in any range:
- Pages 2&ndash;4
- 100&ndash;150 people

## Do's and Don'ts

### Don't use "From" or "To"
Don't use the word "from" or "to" if you're using a dash to show a range.
If you're not using a dash, then you can use "from" and "to." Don't mix these conventions.

- Correct: Lunch break is 1200&ndash;1300. 
- Correct: Lunch break is from 1200 to 1300. 
- Incorrect: Lunch break is from 1200&ndash;1300. 

Another example:

- Incorrect: Nelson Mandela was president of South Africa from 1994&ndash;1999.
- Correct: Nelson Mandela was president of South Africa from 1994 to 1999.
- Incorrect: Homer eats between 60&ndash;75 donuts per month.
- Correct: Homer eats between 60 and 75 donuts per month.

**Comment by samhenrigold** [comment]
I’ve been referencing this blog post a lot lately, thin spaces with an en-dash looks nice. https://clagnut.com/blog/2419

**Comment by danielhaim1** [comment]
That's a great resource. How can I help implement this?
